services:
  backend:
    container_name: mind-tips-backend
    image: mind-tips-backend:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: mind_tips
      DB_SSLMODE: disable
    env_file:
      - .env
    ports:
      - 8080:8080
    volumes:
      - .:/app
      - /app/tmp
    stdin_open: true
    tty: true
    depends_on:
      db:
        condition: service_healthy
  db:
    container_name: mind-tips-db
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mind_tips
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata: {}